# .github/workflows/publish.yml

# Workflow name
name: 'Publish automatically to Chromatic'

# Event for the workflow
on:
  pull_request:
    types:
      - closed
      
# List of jobs
jobs:
  chromatic:
    # Operating System
    runs-on: ubuntu-latest
    # Job steps
    steps:
        - name: Install dependencies
          run: npm install
        - name: Testing
          run: npm test
        - name: Publish to Chromatic
          run: npm run chromatic --project-token=CHROMATIC_PROJECT_TOKEN
