# .github/workflows/publish.yml

# Workflow name
name: 'Publish automatically to Chromatic'

# Event for the workflow
on:
  pull_request:
    types:
      - closed
      
# List of jobs
jobs:
  chromatic:
    if: github.event.pull_request.merged == 'true'
    # Operating System
    runs-on: ubuntu-latest
    # Job steps
    steps:
      - name: Install dependencies
        run: echo "Install dependencies"
        
      - name: PR to review
        run: echo "Pull Request to review"
