# .github/workflows/publish.yml

# Workflow name
name: 'Publish automatically to Chromatic'

# Event for the workflow
on:
  pull_request:
    types:
      - closed
      
# List of jobs
jobs:
  chromatic:
    # Operating System
    runs-on: ubuntu-latest
    # Job steps
    steps:
        - uses: actions/checkout@v1
        - name: Install dependencies
          # 👇 Install dependencies with the same package manager used in the project (replace it as needed), e.g. yarn, npm, pnpm
          run: yarn
          # 👇 Adds Chromatic as a step in the workflow
        - name: Publish to Chromatic
          uses: chromaui/action@v1
          run: npm run chromatic --project-token=CHROMATIC_PROJECT_TOKEN
