# .github/workflows/publish.yml

# Workflow name
name: 'Publish to master on merge'

# Event for the workflow
on:
  pull_request:
    types:
      - closed
      
# List of jobs
jobs:
  if_merged:
    if: github.ref == 'refs/heads/master' && github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
    - run: |
        echo The PR was merged
