# .github/workflows/publish.yml

# Workflow name
name: 'Publish automatically to Chromatic'

# Event for the workflow
on:
  pull_request:
    types:
      - closed
      
# List of jobs
jobs:
  if_merged:
    - run:
    command: npm install # Installs dependencies
    - run:
        command: npm test # Run your unit tests
    - run:
        # 👇 Publish Storybook and run visual tests in Chromatic
        command: npm run chromatic --project-token=CHROMATIC_PROJECT_TOKEN
