# .github/workflows/publish.yml

# Workflow name
name: 'Publish automatically to Chromatic'

# Event for the workflow
on:
  pull_request:
    types:
      - closed
      
# List of jobs
jobs:
  if_merged:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
    - run: |
        echo Publish Chromatic to ${GITHUB_REF#refs/heads/}
